### ISSUE TITLE
Invalid Arguements Error

### ISSUE THREAD

**Issue by Capital-EX** [crystal-ameba/vscode-crystal-ameba#32]
Upon install this extension, I receive the following error:

```
Error: Invalid arguments
	at new f (/home/exarch/Downloads/VSCode-linux-x64/VSCode-linux-x64/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:97:15156)
	at /home/exarch/.vscode/extensions/veelenga.crystal-ameba-0.1.0/out/ameba.js:56:39
	at Array.forEach (<anonymous>)
	at /home/exarch/.vscode/extensions/veelenga.crystal-ameba-0.1.0/out/ameba.js:53:35
	at ChildProcess.exithandler (node:child_process:417:5)
	at ChildProcess.emit (node:events:513:28)
	at maybeClose (node:internal/child_process:1121:16)
	at Socket.<anonymous> (node:internal/child_process:479:11)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:82
```

This happens in the latest version of Visual Studio Code, Code OSS, and Codium.

**Comment by veelenga** [comment]
Thanks for reporting. When you say the latest version, do you mean this one? 

https://github.com/microsoft/vscode/releases/tag/1.79.2

**Comment by Capital-EX** [comment]
Yes, I'm running 1.79.2
